### ISSUE TITLE
Roughing / pockets - only the edges are done, center is missed

### ISSUE THREAD

**Issue by rqhub** [GridSpace/grid-apps#57] opened 2019-02-11 09:27 UTC
The 3 square pockets in this example are 8mm wide, with a 3mm bit. 
They should be 3 passes per level, the algo just makes 2, leaving a stud in the middle
Same result with and without depth first
STL herebelow

Also, travel moves (i don't have the example here), are sometimes done at the wrong z level, provoking crashes (we had this issue some time ago)

**Comment by rqhub** [comment] 2019-02-11 09:29
Sorry, can't neither edit the text, neither attach files. Thank Microsoft. 
Will send them by mail if you need them.

Imgur images here:
https://imgur.com/edN8AdP

**Comment by stewartoallen** [comment] 2020-03-23 01:44
Can you verify if this is still the case?  This code has been substantially re-written.

**Comment by ramkam** [comment] 2020-06-01 18:34
The issue is back. It's missing parts of the roughing. Files & screenshots hereafter [there:[](url)](url
<img width="1010" alt="Capture d’écran 2020-06-01 à 21 29 40" src="https://user-images.githubusercontent.com/2746553/83441560-63aee780-a44f-11ea-975c-5b391b287ffe.png">
<img width="1079" alt="Capture d’écran 2020-06-01 à 21 28 21" src="https://user-images.githubusercontent.com/2746553/83441615-7b866b80-a44f-11ea-837d-b7b70d22c548.png">
[cnc163.zip](https://github.com/GridSpace/grid-apps/files/4712872/cnc163.zip)


)

**Comment by ramkam** [comment] 2020-06-01 18:40
Note that with a stepover of 0.7 instead of 0.8 it seems to work better.
There's definitively an issue though, maybe to taking the last item of an array (improper bound) or by design / way of calculating the path vs tolerances ... anyway, these bugs come back often, i wonder if it's opportune to make more elaborate tests before pushing the release into prod?
<img width="1001" alt="Capture d’écran 2020-06-01 à 21 38 04" src="https://user-images.githubusercontent.com/2746553/83442059-36af0480-a450-11ea-80a3-527604378f01.png">
?

**Comment by stewartoallen** [comment] 2020-06-01 18:43
I don't think anything has changed recently that would cause this. I'm in the process of re-doing the back end to allow for multiple version of Kiri to be hosted simultaneously. That way you can choose which release you want to work with. It will also allow me to have a live branch with highly experimental code.

**Comment by ramkam** [comment] 2020-06-01 19:04
Sounds good to me!
Carefull on not maintaining to many versions in parallel, it's a nightmare

I wonder if there's a way to isolate the slicing & gcode generation from the gui? for ex, calling the slice+gcode from CLI with a reference to a json config file > outputs gcode ?  (as you guessed i'm not up to date in js/node coding :D)

**Comment by stewartoallen** [comment] 2020-06-01 19:08
in this case, the code that's changing would not be in the UI

**Comment by ramkam** [comment] 2020-06-01 19:12
the last point is completely unrelated to the bug. i'm just wondering how to make things more convenient in my "workflow"

**Comment by ramkam** [comment] 2020-06-01 19:14
anyway, don't bother too much, your app is tip top, it does the job good enough, and i haven't encountered bits collisions for a long time now. Thanks.

**Comment by ramkam** [comment] 2020-06-02 19:49
Ok, it happens again, on other models, collisions are back. 
Luckily that one wont break the bit.

<img width="971" alt="Capture d’écran 2020-06-02 à 22 45 23" src="https://user-images.githubusercontent.com/2746553/83562881-fa98a400-a522-11ea-8338-b77b811982f4.png">
<img width="894" alt="Capture d’écran 2020-06-02 à 22 48 24" src="https://user-images.githubusercontent.com/2746553/83563035-3af82200-a523-11ea-99ad-47448ca99467.png">
<img width="872" alt="Capture d’écran 2020-06-02 à 22 48 13" src="https://user-images.githubusercontent.com/2746553/83563061-421f3000-a523-11ea-9435-afb11afbd20c.png">
[cnc166.zip](https://github.com/GridSpace/grid-apps/files/4719344/cnc166.zip)

**Comment by ramkam** [comment] 2020-06-02 19:50
[cnc166.zip](https://github.com/GridSpace/grid-apps/files/4719348/cnc166.zip)

**Comment by stewartoallen** [comment] 2020-06-02 19:51
Can you also send the settings that produced this? Setup -> Export

**Comment by ramkam** [comment] 2020-06-02 19:55
[kiriconf.b64.zip](https://github.com/GridSpace/grid-apps/files/4719383/kiriconf.b64.zip)

**Comment by ramkam** [comment] 2020-06-02 20:03
Somehow, those (crappy) long bits are expensive :-) 

I'm tempted to writing some (python, sorry, already did some voxel stuff in that) code to do collision & bit over loading detection :D 

<img width="401" alt="Capture d’écran 2020-06-02 à 23 00 06" src="https://user-images.githubusercontent.com/2746553/83564219-038a7500-a525-11ea-92a0-72e498673b8a.png">

Is there a more stable version i can download & use locally?

**Comment by stewartoallen** [comment] 2020-06-02 20:08
do you see this in the cut or only in the simulator? i've regenerated the gcode and looked at the one your sent and while I see that diagonal move, it doesn't seem to intersect uncut material in my previewer.

**Comment by ramkam** [comment] 2020-06-02 23:06
not crazy, there were some weird moves, so i replayed it on the simulator, and when i saw the picture above, i stopped it before i had to see a crash or step skips ... 

this said, the CAMotics app never failed me before
ran it twice, at different resolutions, same same
and checked quickly, it's making a 3 mm deep cut, at 100% load, instead of 1 mm

**Comment by ramkam** [comment] 2020-06-02 23:07
<img width="1004" alt="Capture d’écran 2020-06-03 à 02 07 08" src="https://user-images.githubusercontent.com/2746553/83578257-f7abac80-a53e-11ea-8ad1-d3b02399328b.png">
<img width="1010" alt="Capture d’écran 2020-06-03 à 02 04 36" src="https://user-images.githubusercontent.com/2746553/83578265-fed2ba80-a53e-11ea-89a0-37fe842396e3.png">

**Comment by stewartoallen** [comment] 2020-06-02 23:08
there must be a bug in my visualizer and collision detection. will work on it.

**Comment by ramkam** [comment] 2020-06-02 23:13
Wild guess (i don't know how your algo is made): operations to executre are  grouped, and the group is stored in a pile. Then, a decision is made to make one group or the other from the pile; not always the right one; or the length of the pile is miscalc / some op groups stay stuck

**Comment by stewartoallen** [comment] 2020-06-02 23:58
sort of. it's a bit more complex than that because of the way pools (nested groups) can split top down. but this error appears to be in the z height detection of interference between pools.

**Comment by stewartoallen** [comment] 2020-07-06 18:36
A fix has been pushed to production

**Closed by stewartoallen** 2020-07-06 18:36 UTC
